### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by xnacly** [xNaCly/portfolio#1]
- [x] rework light-theme
- [x] rework dark-theme
- [x] fix overflow of code blocks in markdown blog entries on mobile
- [x] add a search to query for text in title and content
- [x] Add a blog page
  - [ ] ~serverless function?~
  - [x] add a ~component~ *script to create blog entries
- [x] update source in footer
- [x] Replace `//` in `src/data/about.json[contact[1]]`
- [x] decrease margin blog info on mobile
- [x] fix mobile view
- [x] Remove contact page
- [x] Add contact in form of icons to about
- [x] Move the content of the about_container to the top of the landingpage
- [x] Replace Select in Navbar with icons
  - [x] change theme based on clicked icon (moon, sun)
- [ ] ~Add dynamic `project/:id` route~
  - [ ] ~render the readme of each project in these~

href:
~https://dilshankelsen.com/how-to-use-url-parameters-in-react-router/~
~https://www.npmjs.com/package/react-markdown~
